# -*- coding: utf-8 -*-
"""Copia de Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5ssN8loR5zQRKmFq0ygF3z9u7zTmV5b
"""

#import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact

# Función de fotosíntesis modificada por CO₂ y luz
def fotosintesis_interactiva(PAR, CO2, Amax_base=20, Km=300, Rd=2):
    """
    CO2: Concentración de CO₂ en ppm (afecta Amax)
    Se asume Amax aumenta logarítmicamente con CO₂.
    """
    Amax = Amax_base * np.log(CO2 / 200 + 1)  # simple aproximación no lineal
    return (Amax * PAR) / (Km + PAR) - Rd

# Función que actualiza el gráfico
def actualizar(CO2=400):
    PAR = np.linspace(0, 2000, 100)
    Pn = fotosintesis_interactiva(PAR, CO2)

    plt.figure(figsize=(8, 5))
    plt.plot(PAR, Pn, color='green')
    plt.title(f'Fotosíntesis vs PAR (CO₂ = {CO2} ppm)')
    plt.xlabel('PAR (µmol m⁻² s⁻¹)')
    plt.ylabel('Fotosíntesis neta (µmol CO₂ m⁻² s⁻¹)')
    plt.axhline(0, color='gray', linestyle='--')
    plt.grid(True)
    plt.ylim(-5, 25)
    plt.show()

# Crear widget interactivo
interact(actualizar, CO2=(100, 1200, 50))

with open('requirements.txt', 'w') as f:
    f.write("streamlit\nmatplotlib\nnumpy\n")





# @title Texto de título predeterminado
app.py

#import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact

# Función de fotosíntesis modificada por CO₂ y luz
def fotosintesis_interactiva(PAR, CO2, Amax_base=20, Km=300, Rd=2):
    """
    CO2: Concentración de CO₂ en ppm (afecta Amax)
    Se asume Amax aumenta logarítmicamente con CO₂.
    """
    Amax = Amax_base * np.log(CO2 / 200 + 1)  # simple aproximación no lineal
    return (Amax * PAR) / (Km + PAR) - Rd

# Función que actualiza el gráfico
def actualizar(CO2=400):
    PAR = np.linspace(0, 2000, 100)
    Pn = fotosintesis_interactiva(PAR, CO2)

    plt.figure(figsize=(8, 5))
    plt.plot(PAR, Pn, color='green')
    plt.title(f'Fotosíntesis vs PAR (CO₂ = {CO2} ppm)')
    plt.xlabel('PAR (µmol m⁻² s⁻¹)')
    plt.ylabel('Fotosíntesis neta (µmol CO₂ m⁻² s⁻¹)')
    plt.axhline(0, color='gray', linestyle='--')
    plt.grid(True)
    plt.ylim(-5, 25)
    plt.show()

# Crear widget interactivo
interact(actualizar, CO2=(100, 1200, 50))